const alumniData = [
  {
    id: 1,
    name: 'John Doe',
    graduationYear: 2010,
    joiningYear: 2006,
    degree: 'B.Sc. Computer Science',
    role: 'Software Engineer',
    house: 'Alpha',
    currentLocation: 'California, USA',
    company: 'Google',
    designation: 'Senior Software Engineer',
    workIndustry: 'Technology',
    otherInstitute: 'Stanford University',
    otherDegree: 'M.Sc. Computer Science',
    otherDepartment: 'Computer Science',
    skills: 'JavaScript, React, Node.js',
    photo: 'src/assets/ipsies.jpg',
    details: 'John has been working at Google for the past 5 years and is currently a Senior Software Engineer.'
  },
  {
    id: 2,
    name: 'Jane Smith',
    graduationYear: 2012,
    joiningYear: 2008,
    degree: 'B.A. Economics',
    role: 'Economist',
    house: 'Beta',
    currentLocation: 'New York, USA',
    company: 'World Bank',
    designation: 'Economist',
    workIndustry: 'Finance',
    otherInstitute: 'Harvard University',
    otherDegree: 'Ph.D. Economics',
    otherDepartment: 'Economics',
    skills: 'Economics, Data Analysis, Policy Making',
    photo: 'src/assets/ipsies.jpg',
    details: 'Jane is an economist at the World Bank and specializes in international development and macroeconomic policy.'
  },
  {
    id: 3,
    name: 'Jane Smith',
    graduationYear: 2012,
    joiningYear: 2008,
    degree: 'B.A. Economics',
    role: 'Economist',
    house: 'Beta',
    currentLocation: 'New York, USA',
    company: 'World Bank',
    designation: 'Economist',
    workIndustry: 'Finance',
    otherInstitute: 'Harvard University',
    otherDegree: 'Ph.D. Economics',
    otherDepartment: 'Economics',
    skills: 'Economics, Data Analysis, Policy Making',
    photo: 'src/assets/ipsies.jpg',
    details: 'Jane is an economist at the World Bank and specializes in international development and macroeconomic policy.'
  },
  {
    id: 4,
    name: 'Jane Smith',
    graduationYear: 2012,
    joiningYear: 2008,
    degree: 'B.A. Economics',
    role: 'Economist',
    house: 'Beta',
    currentLocation: 'New York, USA',
    company: 'World Bank',
    designation: 'Economist',
    workIndustry: 'Finance',
    otherInstitute: 'Harvard University',
    otherDegree: 'Ph.D. Economics',
    otherDepartment: 'Economics',
    skills: 'Economics, Data Analysis, Policy Making',
    photo: 'src/assets/ipsies.jpg',
    details: 'Jane is an economist at the World Bank and specializes in international development and macroeconomic policy.'
  },
  {
    id: 5,
    name: 'Jane Smith',
    graduationYear: 2012,
    joiningYear: 2008,
    degree: 'B.A. Economics',
    role: 'Economist',
    house: 'Beta',
    currentLocation: 'New York, USA',
    company: 'World Bank',
    designation: 'Economist',
    workIndustry: 'Finance',
    otherInstitute: 'Harvard University',
    otherDegree: 'Ph.D. Economics',
    otherDepartment: 'Economics',
    skills: 'Economics, Data Analysis, Policy Making',
    photo: 'src/assets/ipsies.jpg',
    details: 'Jane is an economist at the World Bank and specializes in international development and macroeconomic policy.'
  },
  {
    id: 6,
    name: 'Jane Smith',
    graduationYear: 2012,
    joiningYear: 2008,
    degree: 'B.A. Economics',
    role: 'Economist',
    house: 'Beta',
    currentLocation: 'New York, USA',
    company: 'World Bank',
    designation: 'Economist',
    workIndustry: 'Finance',
    otherInstitute: 'Harvard University',
    otherDegree: 'Ph.D. Economics',
    otherDepartment: 'Economics',
    skills: 'Economics, Data Analysis, Policy Making',
    photo: 'src/assets/ipsies.jpg',
    details: 'Jane is an economist at the World Bank and specializes in international development and macroeconomic policy.'
  },
  // Add more alumni records as needed
];

export default alumniData;
